baseURL = "https://xroot.org/"
languageCode = "en-us"
title = "Tiago's 🏡"
theme = "ink"
paginate = 10
publishDir = "../"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "xroot.org - EST 2006"

	# Optional 64x64 avatar image.
	avatar = ""

	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/3CORESec"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/0xtf"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

